#!/data/data/com.termux/files/usr/bin/bash
# shellr — one-shot installer for a rooted Android phone.
#
# Single-file install. Run on the phone from Termux (or via adb):
#
#   bash install.sh
#
# What it does:
#   1. preflight: must be root + service.d present + Termux python3
#   2. writes /data/local/tmp/shellrd/shellrd.py          (bundled daemon)
#   3. writes /data/local/tmp/shellrd/.shellr_secret      (HMAC key)
#   4. writes /data/adb/service.d/shellrd.sh              (autostart)
#   5. starts the daemon
#   6. prints the Tailscale IP + HMAC secret + control commands
#
# Generated by scripts/build_installer.py from src/shellr/daemon/*.py.
# This file is hermetic — no network or external tools needed beyond
# python3 + bash.
set -eu

INSTALLER_VERSION="0.2.0"
# Canonical home for shellrd on rooted phones is /data/adb/shellrd
# (KernelSU / Magisk convention — see ALLOWED_ROOTS in config.py).
# /data/local/tmp/shellrd is kept as a fallback for backward compatibility.
PHONE_HOME="/data/adb/shellrd"
SERVICE_D="/data/adb/service.d"

banner() { printf '\n=== %s ===\n' "$*"; }
ok()     { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn()   { printf '  \033[33m!\033[0m %s\n' "$*"; }
die()    { printf '  \033[31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# preflight

banner "preflight"

if [ "$(id -u)" -ne 0 ]; then
    die "must be root. Run 'su' first, then re-run this script."
fi
ok "running as root (uid 0)"

if [ ! -d "$SERVICE_D" ]; then
    die "no $SERVICE_D. Is this phone rooted with KernelSU or Magisk?"
fi
ok "service.d directory present"

TERMUX_PY="/data/data/com.termux/files/usr/bin/python3"
[ -x "$TERMUX_PY" ] || die "Termux python not found at $TERMUX_PY — open Termux, run 'pkg install python', then retry"
ok "Termux python3 found at $TERMUX_PY"

# ---------------------------------------------------------------------------
# layout

banner "layout"

mkdir -p "$PHONE_HOME"
chmod 755 "$PHONE_HOME"
ok "$PHONE_HOME ready"

# ---------------------------------------------------------------------------
# write daemon (bundled heredoc)

banner "writing daemon"

cat > "$PHONE_HOME/shellrd.py" <<'DAEMON_EOF'
#!/data/data/com.termux/files/usr/bin/python3
"""shellrd — bundled as a single self-contained file.

Auto-generated from src/shellr/daemon/*.py by
scripts/build_installer.py. Do not edit by hand; edit the
source modules and rerun the builder.
"""

import argparse
import base64
import hashlib
import hmac
import ipaddress
import json
import logging
import os
import shutil
import socket
import subprocess
import sys
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

# Shellr version
__version__ = "0.2.0"


# ======= config.py =======
"""Daemon configuration — defaults, paths, security policy.

Override on the command line via ``--host``, ``--port``, ``--secret``,
``--log``, ``--no-su``, ``--no-tailnet-check``.
"""


# Bind defaults — refuse to start without an explicit --host.
DEFAULT_HOST: str | None = None
DEFAULT_PORT: int = 7777
DEFAULT_SECRET_PATH: str = "/data/adb/shellrd/.shellr_secret"
DEFAULT_LOG_PATH: str = "/sdcard/shellr.log"
DEFAULT_TIMEOUT: int = 30

# Output caps
MAX_OUTPUT_BYTES: int = 256 * 1024     # 256 KiB cap on shell stdout/stderr
MAX_REQUEST_BYTES: int = 1_048_576     # 1 MiB cap on request body
MAX_FILE_READ_BYTES: int = 1_048_576   # 1 MiB cap on a single read

# Tailscale IPv4 CIDR — only accept connections from this range.
# Defence-in-depth on top of HMAC. The boot script passes
# --no-tailnet-check because it binds the daemon directly to a
# Tailscale tunnel IP, so only tunnel traffic can reach it.
TAILNET_CIDR: str | None = "100.64.0.0/10"

# File ops whitelist: paths under these roots are allowed.
# /data/adb/shellrd is the canonical home on rooted phones; we also
# keep legacy /data/local/tmp/shellrd for backward compatibility with
# installs that pre-date the migration.
ALLOWED_ROOTS: tuple[str, ...] = (
    "/data/adb/shellrd",
    "/data/local/tmp/shellrd",
    "/sdcard",
    "/data/local/tmp",
)

# Command patterns to refuse even with root. These are not a sandbox —
# root is root — but they stop stupid copy-paste typos from taking out
# the device.
DESTRUCTIVE_PATTERNS: tuple[str, ...] = (
    "rm -rf /",
    "mkfs",
    "dd if=/dev/zero of=/dev/",
)


# ======= logging.py =======
"""Daemon logging — append-only audit trail.

Every RPC call is logged with: timestamp, method, source IP, duration,
error (if any). Logs go to a file (append, no fsync loop) and stderr
(visible in the calling shell).
"""


import logging
import sys
from pathlib import Path

LOG_FORMAT = "%(asctime)s %(levelname)-5s %(message)s"
DATE_FORMAT = "%Y-%m-%dT%H:%M:%S%z"


def setup_logging(log_path: str) -> logging.Logger:
    """Configure the ``shellrd`` logger: stderr + append-only file."""
    log = logging.getLogger("shellrd")
    log.setLevel(logging.INFO)
    # Avoid duplicate handlers on reload
    log.handlers.clear()

    fmt = logging.Formatter(LOG_FORMAT, datefmt=DATE_FORMAT)

    sh = logging.StreamHandler(sys.stderr)
    sh.setFormatter(fmt)
    log.addHandler(sh)

    try:
        fh = logging.FileHandler(log_path, mode="a", encoding="utf-8")
        fh.setFormatter(fmt)
        log.addHandler(fh)
    except OSError as exc:
        # /sdcard may not be mounted in every boot context — fall back
        # to a tmpfs path so we still have a trail.
        fallback = "/data/local/tmp/shellr.log"
        fh = logging.FileHandler(fallback, mode="a", encoding="utf-8")
        fh.setFormatter(fmt)
        log.addHandler(fh)
        log.warning("could not open %s (%s); logging to %s instead",
                    log_path, exc, fallback)

    return log


# ======= exec.py =======
"""Daemon execution layer.

Three capabilities:

- :func:`run_shell` — run a command as root, with timeout and output cap.
- :func:`file_read`, :func:`file_write`, :func:`file_list` — file ops
  restricted to :data:`shellr.daemon.config.ALLOWED_ROOTS`.
- :func:`dispatch` — RPC method → handler dispatch.

The daemon runs as root in production. On the VPS-side smoke test we
invoke with ``--no-su`` so commands run directly without root.
"""


import base64
import ipaddress
import os
import shutil
import subprocess
import time
from pathlib import Path



# ---------------------------------------------------------------------------
# Pre-flight: where's `su`?
# ---------------------------------------------------------------------------

def _has_su() -> bool:
    """True if ``su`` is somewhere on PATH or at the standard locations."""
    return (
        os.path.isfile("/system/bin/su")
        or os.path.isfile("/system/xbin/su")
        or os.path.isfile("/sbin/su")
        or shutil.which("su") is not None
    )


# ---------------------------------------------------------------------------
# Shell exec
# ---------------------------------------------------------------------------

def run_shell(command: str, timeout: int, force_su: bool = False) -> dict:
    """Run ``command`` as root via ``/system/bin/sh -c``.

    On a daemon already running as root, ``force_su=False`` runs the
    command directly (no ``su -c`` indirection). On a daemon running as
    a non-root user with ``su`` available, falls back to ``su -c``.

    Returns::

        {"ok": bool, "stdout": str, "stderr": str, "code": int,
         "duration_ms": int, "timed_out": bool, "truncated": bool}
    """
    if timeout <= 0 or timeout > 300:
        timeout = DEFAULT_TIMEOUT

    # Pre-exec safety: refuse obviously hostile patterns.
    if any(p in command for p in DESTRUCTIVE_PATTERNS):
        return {
            "ok": False,
            "stdout": "",
            "stderr": "refused: command matches destructive pattern",
            "code": -1,
            "duration_ms": 0,
            "timed_out": False,
            "truncated": False,
        }

    # --no-su (force_su=False): never use su, even if we're not root.
    # default (force_su=True): use su only when we're not already root.
    use_su = force_su and os.geteuid() != 0
    # /system/bin/sh is Android-specific; /bin/sh is portable. Detect.
    shell_bin = "/system/bin/sh" if os.path.isfile("/system/bin/sh") else "/bin/sh"
    full = ["su", "-c", command] if use_su else [shell_bin, "-c", command]

    t0 = time.monotonic()
    try:
        proc = subprocess.run(
            full,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
            start_new_session=True,
        )
    except subprocess.TimeoutExpired as exc:
        duration_ms = int((time.monotonic() - t0) * 1000)
        return {
            "ok": False,
            "stdout": (exc.stdout or b"").decode(errors="replace")[:MAX_OUTPUT_BYTES],
            "stderr": (exc.stderr or b"").decode(errors="replace")[:MAX_OUTPUT_BYTES],
            "code": -1,
            "duration_ms": duration_ms,
            "timed_out": True,
            "truncated": False,
        }

    duration_ms = int((time.monotonic() - t0) * 1000)
    out, err = proc.stdout, proc.stderr
    truncated = False
    if len(out) > MAX_OUTPUT_BYTES:
        out = out[:MAX_OUTPUT_BYTES] + "\n...[truncated]"
        truncated = True
    if len(err) > MAX_OUTPUT_BYTES:
        err = err[:MAX_OUTPUT_BYTES] + "\n...[truncated]"
        truncated = True

    return {
        "ok": proc.returncode == 0,
        "stdout": out,
        "stderr": err,
        "code": proc.returncode,
        "duration_ms": duration_ms,
        "timed_out": False,
        "truncated": truncated,
    }


# ---------------------------------------------------------------------------
# File ops (whitelisted)
# ---------------------------------------------------------------------------

def _check_path(p: str) -> str:
    """Resolve ``p``; raise :class:`ValueError` if outside ALLOWED_ROOTS."""
    rp = str(Path(p).expanduser().resolve(strict=False))
    rp_path = Path(rp)
    for root in ALLOWED_ROOTS:
        try:
            rp_path.resolve(strict=False).relative_to(Path(root).resolve(strict=False))
            return rp
        except ValueError:
            continue
    raise ValueError(f"path {p!r} not under any allowed root")


def file_read(path: str, max_bytes: int = MAX_FILE_READ_BYTES) -> dict:
    rp = _check_path(path)
    with open(rp, "rb") as f:
        data = f.read(max_bytes + 1)
    truncated = len(data) > max_bytes
    if truncated:
        data = data[:max_bytes]
    return {
        "path": rp,
        "size": len(data),
        "truncated": truncated,
        "content_b64": base64.b64encode(data).decode(),
    }


def file_write(path: str, content_b64: str) -> dict:
    rp = _check_path(path)
    data = base64.b64decode(content_b64)
    with open(rp, "wb") as f:
        f.write(data)
    return {"path": rp, "size": len(data)}


def file_list(path: str) -> dict:
    rp = _check_path(path)
    entries = []
    for entry in sorted(Path(rp).iterdir()):
        try:
            st = entry.stat()
            entries.append({
                "name": entry.name,
                "is_dir": entry.is_dir(),
                "size": st.st_size,
                "mtime": int(st.st_mtime),
            })
        except OSError:
            entries.append({"name": entry.name, "error": "stat failed"})
    return {"path": rp, "entries": entries}


# ---------------------------------------------------------------------------
# Method dispatch
# ---------------------------------------------------------------------------

def _android_sdk() -> str:
    try:
        with open("/system/build.prop") as f:
            for line in f:
                if line.startswith("ro.build.version.sdk="):
                    return line.split("=", 1)[1].strip()
                if line.startswith("ro.build.version.release="):
                    return line.split("=", 1)[1].strip()
    except OSError:
        pass
    return "unknown"


def _tailscale_ip() -> str:
    try:
        out = subprocess.run(
            ["tailscale", "ip", "-4"],
            capture_output=True, text=True, timeout=3,
        )
        return out.stdout.strip().splitlines()[0] if out.stdout else ""
    except Exception:
        return ""


def _make_dispatch(use_su: bool):
    """Build a dispatch() closure bound to ``use_su`` policy."""
    def dispatch(method: str, params: dict) -> dict:
        if method == "ping":
            return {
                "pong": True,
                "ts": int(time.time()),
                "uid": os.getuid(),
                "euid": os.geteuid(),
                "host": os.uname().nodename,
                "uptime_s": int(time.time() - Path("/proc").stat().st_mtime),
            }

        if method in ("shell", "shell_sudo"):
            cmd = params.get("command") or params.get("cmd")
            if not cmd or not isinstance(cmd, str):
                return {"ok": False, "error": "missing 'command' string"}
            timeout = int(params.get("timeout", DEFAULT_TIMEOUT))
            return run_shell(cmd, timeout, force_su=use_su)

        if method == "read":
            return file_read(params["path"], int(params.get("max_bytes", MAX_FILE_READ_BYTES)))

        if method == "write":
            return file_write(params["path"], params["content_b64"])

        if method == "list":
            return file_list(params["path"])

        if method == "info":
            return {
                "host": os.uname().nodename,
                "kernel": os.uname().release,
                "android_sdk": _android_sdk(),
                "termux": os.environ.get("PREFIX", ""),
                "uid": os.getuid(),
                "euid": os.geteuid(),
                "tailscale_ip": _tailscale_ip(),
            }

        return {"ok": False, "error": f"unknown method {method!r}"}

    return dispatch


def tailnet_check(source_ip: str) -> bool:
    """Return True if ``source_ip`` is in the configured Tailscale CIDR."""
    if not TAILNET_CIDR:
        return True
    try:
        addr = ipaddress.ip_address(source_ip)
        net = ipaddress.ip_network(TAILNET_CIDR, strict=False)
        return addr in net
    except ValueError:
        return False


# ======= server.py =======
"""HTTP transport — the daemon's only network surface.

A :class:`ThreadingHTTPServer` subclass threads the secret into the
handler (one thread per request; cheap, sleeps on kernel epoll when idle).

Routes:
    GET  /health       — open liveness probe
    POST /             — RPC entry; HMAC + tailnet-CIDR enforced
"""


import json
import logging
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

from shellr.crypto import verify as hmac_verify

log = logging.getLogger("shellrd.http")


# ---------------------------------------------------------------------------
# Server builder
# ---------------------------------------------------------------------------

def build_server(
    *,
    host: str,
    port: int,
    secret_path: str,
    log_path: str,
    use_su: bool,
    check_tailnet: bool,
):
    """Load the secret, wire up the handler, return an unstarted server."""
    from shellr.daemon.logging import setup_logging
    setup_logging(log_path)

    secret = _load_secret(secret_path)
    dispatch = _make_dispatch(use_su=use_su)

    handler_cls = _make_handler(
        secret=secret,
        dispatch=dispatch,
        check_tailnet=check_tailnet,
    )

    server = ShellrServer((host, port), handler_cls)
    log.info("shellrd listening on %s:%d (secret=%d bytes, log=%s)",
             host, port, len(secret), log_path)
    log.info("allowed roots: %s", _format_allowed_roots())
    return server


def _format_allowed_roots() -> str:
    from shellr.daemon.config import ALLOWED_ROOTS
    return ", ".join(ALLOWED_ROOTS)


def _load_secret(path: str) -> bytes:
    p = Path(path)
    if not p.exists():
        raise SystemExit(
            f"shellrd: secret not found at {path}\n"
            f"  generate one with: openssl rand -hex 32\n"
            f"  then: echo '<hex>' > {path} && chmod 600 {path}"
        )
    mode = p.stat().st_mode & 0o777
    if mode & 0o077:
        raise SystemExit(
            f"shellrd: REFUSING to start — {path} is mode {oct(mode)}, "
            "must be 600 or 400. Fix with: chmod 600 <path>"
        )
    return p.read_bytes().strip()


def run_server(server) -> int:
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        log.info("shellrd interrupted, shutting down")
        server.shutdown()
    return 0


# ---------------------------------------------------------------------------
# Handler factory
# ---------------------------------------------------------------------------

def _make_handler(*, secret: bytes, dispatch, check_tailnet: bool):
    """Closure → handler subclass with bound secret + dispatch."""

    class ShellrHandler(BaseHTTPRequestHandler):
        server_version = "shellrd/1.0"

        # Quiet the default per-request stderr noise.
        def log_message(self, fmt, *args):
            pass

        # ------------------------------------------------------------------
        # routing
        # ------------------------------------------------------------------

        def do_POST(self):  # noqa: N802
            if self.path == "/":
                self._handle_root()
            elif self.path == "/health":
                self._handle_health()
            else:
                self.send_error(404, "unknown path")

        def do_GET(self):  # noqa: N802
            if self.path == "/health":
                self._handle_health()
            else:
                self.send_error(404, "unknown path")

        # ------------------------------------------------------------------
        # handlers
        # ------------------------------------------------------------------

        def _handle_health(self):
            body = json.dumps({
                "ok": True, "service": "shellrd", "ts": int(time.time()),
            }).encode()
            self._write(200, body)

        def _handle_root(self):
            # Tailnet CIDR check — defence in depth on top of HMAC.
            if check_tailnet and not tailnet_check(self.client_address[0]):
                log.warning("rejected non-tailnet source %s",
                            self.client_address[0])
                return self._write_json(403, {
                    "ok": False, "error": "source not in tailnet",
                })

            # Read body
            try:
                length = int(self.headers.get("Content-Length") or 0)
            except ValueError:
                return self._write_json(400, {
                    "ok": False, "error": "bad Content-Length",
                })
            if length <= 0 or length > MAX_REQUEST_BYTES:
                return self._write_json(400, {
                    "ok": False, "error": "bad Content-Length",
                })
            body = self.rfile.read(length)

            # Verify HMAC
            sig = self.headers.get("X-Shellr-Signature", "")
            if not hmac_verify(secret, body, sig):
                log.warning("HMAC mismatch from %s — body=%d bytes sig=%s...",
                            self.client_address[0], len(body), sig[:8])
                return self._write_json(401, {
                    "ok": False, "error": "bad signature",
                })

            # Parse
            try:
                req = json.loads(body)
            except json.JSONDecodeError as exc:
                return self._write_json(400, {
                    "ok": False, "error": f"bad json: {exc}",
                })
            method = req.get("method")
            params = req.get("params") or {}
            if not isinstance(params, dict):
                return self._write_json(400, {
                    "ok": False, "error": "params must be object",
                })
            if not isinstance(method, str):
                return self._write_json(400, {
                    "ok": False, "error": "method must be string",
                })

            # Dispatch + audit
            t0 = time.monotonic()
            try:
                result = dispatch(method, params)
                err = None
            except Exception as exc:
                result = None
                err = f"{type(exc).__name__}: {exc}"
            dt_ms = int((time.monotonic() - t0) * 1000)

            log.info("rpc method=%s from=%s dt_ms=%d err=%s",
                     method, self.client_address[0], dt_ms, err)

            body_out = json.dumps({
                "ok": err is None,
                "method": method,
                "result": result,
                "error": err,
                "dt_ms": dt_ms,
            }).encode()
            self._write(200, body_out)

        # ------------------------------------------------------------------
        # helpers
        # ------------------------------------------------------------------

        def _write(self, code: int, body: bytes):
            self.send_response(code)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def _write_json(self, code: int, payload: Any):
            self._write(code, json.dumps(payload).encode())

    return ShellrHandler


# ---------------------------------------------------------------------------
# Server
# ---------------------------------------------------------------------------

class ShellrServer(ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True


# ======= __init__.py =======
"""shellrd — the phone-side daemon.

Runs on the rooted Android, listens ONLY on the Tailscale tunnel IP, talks
JSON-RPC over HTTP. Every request is HMAC-SHA256 signed. Every exec runs
as root directly (no ``su`` indirection when running as uid 0). Every
request is audit-logged to ``/sdcard/shellr.log``.

Module layout:

    shellr.daemon        # you are here — main entry point
    shellr.daemon.config  # DEFAULT_HOST, DEFAULT_PORT, ALLOWED_ROOTS, ...
    shellr.daemon.exec    # run_shell(), file_read/write/list(), dispatch
    shellr.daemon.server  # HTTP handler + ThreadingHTTPServer subclass

Run with::

    python -m shellr.daemon --host 100.x.y.z --port 7777 \\
        --secret /data/adb/shellrd/.shellr_secret
"""


import argparse
import logging
import sys


log = logging.getLogger("shellrd")


def _parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        prog="shellrd",
        description="shellr daemon — phone-side RPC over Tailscale",
    )
    ap.add_argument("--host", default=DEFAULT_HOST,
                    help="IP to bind to (default: %(default)s)")
    ap.add_argument("--port", type=int, default=DEFAULT_PORT,
                    help="port to listen on (default: %(default)s)")
    ap.add_argument("--secret", default=DEFAULT_SECRET_PATH,
                    help="path to the HMAC pre-shared key (hex)")
    ap.add_argument("--log", default=DEFAULT_LOG_PATH,
                    help="audit log path")
    ap.add_argument("--no-su", action="store_true",
                    help="never use `su -c`; run commands directly "
                         "(only safe when already root, useful for tests)")
    ap.add_argument("--no-tailnet-check", action="store_true",
                    help="disable the tailnet CIDR source-IP check "
                         "(useful when the daemon is bound directly to "
                         "the Tailscale tunnel IP)")
    return ap.parse_args()


def main() -> int:
    args = _parse_args()

    if not args.host:
        sys.stderr.write(
            "shellrd: --host is required (the IP to bind to). "
            "Pick a Tailscale tunnel IP like 100.x.y.z, not 0.0.0.0.\n"
            "  e.g. --host 100.111.121.72\n"
        )
        return 2
    if args.host in ("0.0.0.0", "") and not args.no_tailnet_check:
        sys.stderr.write(
            "shellrd: refusing to bind to 0.0.0.0 without --no-tailnet-check\n"
            "  bind to a specific Tailscale tunnel IP instead\n"
        )
        return 2

    server = build_server(
        host=args.host,
        port=args.port,
        secret_path=args.secret,
        log_path=args.log,
        use_su=not args.no_su,
        check_tailnet=not args.no_tailnet_check,
    )
    return run_server(server)


if __name__ == "__main__":
    sys.exit(main())


DAEMON_EOF

chmod 700 "$PHONE_HOME/shellrd.py"
ok "wrote daemon at $PHONE_HOME/shellrd.py"

# ---------------------------------------------------------------------------
# write autostart (KernelSU service.d)

banner "writing autostart"

cat > "$SERVICE_D/shellrd.sh" <<'AUTOSTART_EOF'
#!/system/bin/sh
# shellrd auto-start — Tailscale-aware, IP-change-aware, idempotent.

DAEMON=/data/adb/shellrd/shellrd.py
SECRET=/data/adb/shellrd/.shellr_secret
LOG=/sdcard/shellr.log
IP_CACHE=/data/adb/shellrd/.last_ip
FALLBACK=100.111.121.72
BOOT_WAIT=300
POLL_INTERVAL=5

TERMUX_BIN=/data/data/com.termux/files/usr/bin
TERMUX_HOME=/data/data/com.termux/files/usr

export PATH="$TERMUX_BIN:$PATH"
export PYTHONHOME="$TERMUX_HOME"
export LD_LIBRARY_PATH="$TERMUX_HOME/lib:${LD_LIBRARY_PATH:-}"

[ -f "$DAEMON" ]  || { echo "[shellrd] daemon missing"; exit 0; }
[ -f "$SECRET" ]  || { echo "[shellrd] secret missing"; exit 0; }

echo "[shellrd] python3: $(which python3 2>/dev/null || echo MISSING)"
echo "[shellrd] nmap:    $(which nmap 2>/dev/null || echo 'not installed')"

discover_ip() {
    IP=$(ip -4 addr show tun0 2>/dev/null | awk '/inet 100\./ {print $2}' | cut -d/ -f1 | head -1)
    if [ -z "$IP" ] && [ -f "$IP_CACHE" ]; then
        CACHED=$(cat "$IP_CACHE" 2>/dev/null)
        case "$CACHED" in 100.*) IP="$CACHED" ;; esac
    fi
    [ -z "$IP" ] && IP="$FALLBACK"
    echo "$IP"
}

CURRENT_IP=$(discover_ip)

if pgrep -f shellrd.py >/dev/null; then
    if [ -f "$IP_CACHE" ] && [ "$(cat "$IP_CACHE" 2>/dev/null)" != "$CURRENT_IP" ]; then
        echo "[shellrd] IP changed $(cat "$IP_CACHE") -> $CURRENT_IP, restarting"
        pkill -f shellrd.py
        sleep 2
    else
        echo "[shellrd] already running on $CURRENT_IP"
        exit 0
    fi
fi

echo "[shellrd] waiting for Tailscale tunnel (up to ${BOOT_WAIT}s)..."
end=$(( $(date +%s) + BOOT_WAIT ))
while [ $(date +%s) -lt $end ]; do
    if ip -4 addr show tun0 2>/dev/null | grep -q "inet 100\\."; then break; fi
    sleep $POLL_INTERVAL
done

CURRENT_IP=$(discover_ip)
echo "$CURRENT_IP" > "$IP_CACHE" 2>/dev/null
echo "[shellrd] starting on $CURRENT_IP"

( setsid env PATH="$PATH" PYTHONHOME="$PYTHONHOME" \
    python3 "$DAEMON" \
    > "$LOG" 2>&1 < /dev/null & )

sleep 2
if pgrep -f shellrd.py >/dev/null; then
    echo "[shellrd] started OK"
else
    echo "[shellrd] FAILED to start:"
    tail -5 "$LOG" 2>/dev/null
    exit 1
fi
exit 0
AUTOSTART_EOF

chmod 755 "$SERVICE_D/shellrd.sh"
ok "wrote autostart at $SERVICE_D/shellrd.sh"

# ---------------------------------------------------------------------------
# generate or keep existing secret

banner "secret"

SECRET="$PHONE_HOME/.shellr_secret"

if [ -f "$SECRET" ]; then
    EXISTING_SECRET=$(cat "$SECRET")
    warn "secret already exists — keeping it"
else
    EXISTING_SECRET=$("$TERMUX_PY" -c 'import secrets; print(secrets.token_hex(32))')
    printf '%s' "$EXISTING_SECRET" > "$SECRET"
    chmod 600 "$SECRET"
    ok "generated new HMAC secret at $SECRET"
fi

# ---------------------------------------------------------------------------
# start

banner "starting daemon"

"$SERVICE_D/shellrd.sh" || warn "autostart reported FAILED"

sleep 2

DAEMON_PID=$(pgrep -f shellrd.py || echo "")
if [ -n "$DAEMON_PID" ]; then
    ok "daemon PID $DAEMON_PID"
else
    warn "daemon did NOT start. check /sdcard/shellr.log:"
    tail -10 /sdcard/shellr.log 2>/dev/null || true
fi

# ---------------------------------------------------------------------------
# discover IP

banner "Tailscale IP"

TAILSCALE_IP=""
if command -v tailscale >/dev/null 2>&1; then
    TAILSCALE_IP=$(tailscale ip -4 2>/dev/null | head -1 || echo "")
fi
if [ -z "$TAILSCALE_IP" ]; then
    TAILSCALE_IP=$(ip -4 addr show tun0 2>/dev/null \
                   | awk '/inet 100\./ {print $2}' | cut -d/ -f1 | head -1)
fi
[ -z "$TAILSCALE_IP" ] && TAILSCALE_IP="unknown"
ok "phone Tailscale IP: $TAILSCALE_IP"

# ---------------------------------------------------------------------------
# final report

cat <<DONE

=== INSTALL COMPLETE ===

  Phone-side daemon is running and listening on $TAILSCALE_IP:7777.
  Nothing to do on the phone side from here on — it's autostart-
  resilient across reboots.

  FROM YOUR VPS / CONTROLLER:
  ==========================

  1. Save the HMAC secret BELOW to ~/.shellr_secret (chmod 600).
     This is the line you MUST copy verbatim into a file:

         $EXISTING_SECRET

     Quick way on your laptop:

         echo "$EXISTING_SECRET" > ~/.shellr_secret
         chmod 600 ~/.shellr_secret

  2. Install the shellr Python client:

         pip install -e ".[dev]"            # if you cloned the repo
         # or, from anywhere:
         pip install git+https://github.com/nimitbhardwaj/shellr.git

  3. Verify:

         shellr --resolve                 # should print $TAILSCALE_IP
         shellr ping                      # should print pong, uid 0
         shellr info                      # kernel, sdk, ...

  If you can't connect: check that your VPS is on Tailscale
  (`tailscale status` should list 'nimits-a51' as online).

  Files now on the phone:
    /data/local/tmp/shellrd/shellrd.py       (chmod 700)
    /data/local/tmp/shellrd/.shellr_secret   (chmod 600)
    /data/adb/service.d/shellrd.sh           (chmod 755)
    /sdcard/shellr.log                       (chmod 644, append-only)

  Audit trail:
    adb shell 'tail -f /sdcard/shellr.log'    # live RPC log

DONE
