#!/data/data/com.termux/files/usr/bin/bash
# shellr — one-shot installer for a rooted Android phone.
#
# Single-file install. Run on the phone from Termux (or via adb):
#
#   bash install.sh
#
# What it does:
#   1. preflight: must be root + service.d present + Termux python3
#   2. writes /data/adb/shellrd/shellrd.py             (bundled daemon, canonical)
#   3. writes /data/adb/shellrd/.shellr_secret         (HMAC key)
#   4. writes /data/adb/service.d/shellrd.sh           (autostart)
#   5. starts the daemon
#   6. prints the Tailscale IP + HMAC secret + control commands
#
# Generated by scripts/build_installer.py from src/shellr/daemon/*.py.
# This file is hermetic — no network or external tools needed beyond
# python3 + bash.
set -eu

INSTALLER_VERSION="0.2.0"
# Canonical home for shellrd on rooted phones is /data/adb/shellrd
# (KernelSU / Magisk convention — see ALLOWED_ROOTS in config.py).
PHONE_HOME="/data/adb/shellrd"
SERVICE_D="/data/adb/service.d"

banner() { printf '\n=== %s ===\n' "$*"; }
ok()     { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn()   { printf '  \033[33m!\033[0m %s\n' "$*"; }
die()    { printf '  \033[31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# preflight

banner "preflight"

if [ "$(id -u)" -ne 0 ]; then
    die "must be root. Run 'su' first, then re-run this script."
fi
ok "running as root (uid 0)"

if [ ! -d "$SERVICE_D" ]; then
    die "no $SERVICE_D. Is this phone rooted with KernelSU or Magisk?"
fi
ok "service.d directory present"

TERMUX_PY="/data/data/com.termux/files/usr/bin/python3"
[ -x "$TERMUX_PY" ] || die "Termux python not found at $TERMUX_PY — open Termux, run 'pkg install python', then retry"
ok "Termux python3 found at $TERMUX_PY"

# ---------------------------------------------------------------------------
# layout

banner "layout"

mkdir -p "$PHONE_HOME"
chmod 755 "$PHONE_HOME"
ok "$PHONE_HOME ready"

# ---------------------------------------------------------------------------
# write daemon (bundled heredoc)

banner "writing daemon"

cat > "$PHONE_HOME/shellrd.py" <<'DAEMON_EOF'
DAEMON_HEREDOC_PLACEHOLDER
DAEMON_EOF

chmod 700 "$PHONE_HOME/shellrd.py"
ok "wrote daemon at $PHONE_HOME/shellrd.py"

# ---------------------------------------------------------------------------
# write autostart (KernelSU service.d)

banner "writing autostart"

cat > "$SERVICE_D/shellrd.sh" <<'AUTOSTART_EOF'
#!/system/bin/sh
# shellrd auto-start — Tailscale-aware, IP-change-aware, idempotent.

DAEMON=/data/adb/shellrd/shellrd.py
SECRET=/data/adb/shellrd/.shellr_secret
LOG=/sdcard/shellr.log
IP_CACHE=/data/adb/shellrd/.last_ip
FALLBACK=100.111.121.72
BOOT_WAIT=300
POLL_INTERVAL=5

TERMUX_BIN=/data/data/com.termux/files/usr/bin
TERMUX_HOME=/data/data/com.termux/files/usr

export PATH="$TERMUX_BIN:$PATH"
export PYTHONHOME="$TERMUX_HOME"
export LD_LIBRARY_PATH="$TERMUX_HOME/lib:${LD_LIBRARY_PATH:-}"

[ -f "$DAEMON" ]  || { echo "[shellrd] daemon missing"; exit 0; }
[ -f "$SECRET" ]  || { echo "[shellrd] secret missing"; exit 0; }

echo "[shellrd] python3: $(which python3 2>/dev/null || echo MISSING)"
echo "[shellrd] nmap:    $(which nmap 2>/dev/null || echo 'not installed')"

discover_ip() {
    IP=$(ip -4 addr show tun0 2>/dev/null | awk '/inet 100\./ {print $2}' | cut -d/ -f1 | head -1)
    if [ -z "$IP" ] && [ -f "$IP_CACHE" ]; then
        CACHED=$(cat "$IP_CACHE" 2>/dev/null)
        case "$CACHED" in 100.*) IP="$CACHED" ;; esac
    fi
    [ -z "$IP" ] && IP="$FALLBACK"
    echo "$IP"
}

CURRENT_IP=$(discover_ip)

if pgrep -f shellrd.py >/dev/null; then
    if [ -f "$IP_CACHE" ] && [ "$(cat "$IP_CACHE" 2>/dev/null)" != "$CURRENT_IP" ]; then
        echo "[shellrd] IP changed $(cat "$IP_CACHE") -> $CURRENT_IP, restarting"
        pkill -f shellrd.py
        sleep 2
    else
        echo "[shellrd] already running on $CURRENT_IP"
        exit 0
    fi
fi

echo "[shellrd] waiting for Tailscale tunnel (up to ${BOOT_WAIT}s)..."
end=$(( $(date +%s) + BOOT_WAIT ))
while [ $(date +%s) -lt $end ]; do
    if ip -4 addr show tun0 2>/dev/null | grep -q "inet 100\\."; then break; fi
    sleep $POLL_INTERVAL
done

CURRENT_IP=$(discover_ip)
echo "$CURRENT_IP" > "$IP_CACHE" 2>/dev/null
echo "[shellrd] starting on $CURRENT_IP"

( setsid env PATH="$PATH" PYTHONHOME="$PYTHONHOME" \
    python3 "$DAEMON" \
    > "$LOG" 2>&1 < /dev/null & )

sleep 2
if pgrep -f shellrd.py >/dev/null; then
    echo "[shellrd] started OK"
else
    echo "[shellrd] FAILED to start:"
    tail -5 "$LOG" 2>/dev/null
    exit 1
fi
exit 0
AUTOSTART_EOF

chmod 755 "$SERVICE_D/shellrd.sh"
ok "wrote autostart at $SERVICE_D/shellrd.sh"

# ---------------------------------------------------------------------------
# generate or keep existing secret

banner "secret"

SECRET="$PHONE_HOME/.shellr_secret"

if [ -f "$SECRET" ]; then
    EXISTING_SECRET=$(cat "$SECRET")
    warn "secret already exists — keeping it"
else
    EXISTING_SECRET=$("$TERMUX_PY" -c 'import secrets; print(secrets.token_hex(32))')
    printf '%s' "$EXISTING_SECRET" > "$SECRET"
    chmod 600 "$SECRET"
    ok "generated new HMAC secret at $SECRET"
fi

# ---------------------------------------------------------------------------
# start

banner "starting daemon"

"$SERVICE_D/shellrd.sh" || warn "autostart reported FAILED"

sleep 2

DAEMON_PID=$(pgrep -f shellrd.py || echo "")
if [ -n "$DAEMON_PID" ]; then
    ok "daemon PID $DAEMON_PID"
else
    warn "daemon did NOT start. check /sdcard/shellr.log:"
    tail -10 /sdcard/shellr.log 2>/dev/null || true
fi

# ---------------------------------------------------------------------------
# discover IP

banner "Tailscale IP"

TAILSCALE_IP=""
if command -v tailscale >/dev/null 2>&1; then
    TAILSCALE_IP=$(tailscale ip -4 2>/dev/null | head -1 || echo "")
fi
if [ -z "$TAILSCALE_IP" ]; then
    TAILSCALE_IP=$(ip -4 addr show tun0 2>/dev/null \
                   | awk '/inet 100\./ {print $2}' | cut -d/ -f1 | head -1)
fi
[ -z "$TAILSCALE_IP" ] && TAILSCALE_IP="unknown"
ok "phone Tailscale IP: $TAILSCALE_IP"

# ---------------------------------------------------------------------------
# final report

cat <<DONE

=== INSTALL COMPLETE ===

  Phone-side daemon is running and listening on $TAILSCALE_IP:7777.
  Nothing to do on the phone side from here on — it's autostart-
  resilient across reboots.

  FROM YOUR VPS / CONTROLLER:
  ==========================

  1. Save the HMAC secret BELOW to ~/.shellr_secret (chmod 600).
     This is the line you MUST copy verbatim into a file:

         $EXISTING_SECRET

     Quick way on your laptop:

         echo "$EXISTING_SECRET" > ~/.shellr_secret
         chmod 600 ~/.shellr_secret

  2. Install the shellr Python client:

         pip install -e ".[dev]"            # if you cloned the repo
         # or, from anywhere:
         pip install git+https://github.com/nimitbhardwaj/shellr.git

  3. Verify:

         shellr --resolve                 # should print $TAILSCALE_IP
         shellr ping                      # should print pong, uid 0
         shellr info                      # kernel, sdk, ...

  If you can't connect: check that your VPS is on Tailscale
  (`tailscale status` should list 'nimits-a51' as online).

  Files now on the phone:
    /data/adb/shellrd/shellrd.py          (chmod 700)
    /data/adb/shellrd/.shellr_secret      (chmod 600)
    /data/adb/service.d/shellrd.sh        (chmod 755)
    /sdcard/shellr.log                    (chmod 644, append-only)

  Audit trail:
    adb shell 'tail -f /sdcard/shellr.log'    # live RPC log

DONE
